openapi: 3.0.0
info: 
  title: premier devoir api sur json
  version: 1.0.0

servers: 
  - url : http://localhost:3000/api
    description : Ajout de json

paths: 
  /users:
    get:
      summary : retourne un json avec page et size
      operationId: getUsers
      tags: 
        - Users
      parameters: 
        - name : page
          in : query
          description : recuperation de la page
          schema:
            type: integer
            default : 1
        - name : size
          in : query
          schema:
            type: integer
            minimum : 1
            maximum : 200

      responses: 
        '200':
           description: vous obtenner un utilisateur avec succes

