openapi: 3.0.0
info:
  title: tasks lists
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: get post put with json

paths:
  /tasks:
    get:
      summary: retourne la liste des tâches
      description: toutes les listes de tâches sont retournées
      tags:
        - tasks
      responses:
        '200':
          description: liste de toutes les tâches
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tasks'
    post:
      summary: créer une nouvelle tâche
      tags:
        - tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTask'
      responses:
        '201':
          description: tâche ajoutée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tasks'

  /tasks/{id}:
    get : 
      summary: retourne la tache par son id
      description : retourne la tache specifié
      tags :
      - tasks
      parameters :
        - name: id
          in : path 
          required : true
          schema : 
            type: integer
      requestBody: 
        required : true
        content: 
          application/json :
            schema : 
              type: integer
              minimum : 1
      responses: 
        '200':
          description: voici la tache 
          content:
            application/json :
              schema : 
                type: object 
                properties: 
                  data: 
                    type : array 
                    items: 
                      $ref : '#/components/schemas/Tasks'

    put:
      summary: mettre à jour une tâche par son id
      description: la tâche a été mise à jour
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTask'
      responses:
        '200':
          description: votre tâche est mise à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tasks'
        '404':
          description: id non trouvé
    delete:
      summary: supprimer une tâche par son id
      description: votre tâche a été supprimée
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: votre tâche a été supprimée
        '404':
          description: id non trouvé

components:
  schemas:
    Tasks:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: doing chores
        completed:
          type: boolean
          example: false

    CreateTask:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: 'take a rest'
        completed:
          type: boolean
          example: false

    UpdateTask:
      type: object
      properties:
        title:
          type: string
          example: 'new chores'
        completed:
          type: boolean
          example: true